# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b139540e22e23233e7b810fadf3bfe043e9d14309547533e256b21a59d0e2984baf2dabf87817b2c21a392c026a19ecdb7d1568ff28defc8dfe27695a1e05011

test:
  secret_key_base: f64616bf6ec93770373a4d4ef22017102b2b276406b4c3be6c6cfbc731f253fb98deddede86021fcfc879d44d410fef67eacdcb5e0f0b2ba915eeb0fbf806148

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
